### ISSUE TITLE
Expose TestCluster?

### ISSUE THREAD

**Issue by jturkel** [zendesk/ruby-kafka#192] opened 2016-05-20 14:11 UTC
Applications that use Kafka often need to startup and manage Kafka clusters as part of their tests. The [test_kafka](https://github.com/bts/test_kafka) gem does this but it only works with Kafka 0.8 and it relies on the unmaintained [poseidon](https://github.com/bpot/poseidon) gem. Any interest in exposing the ruby-kafka `TestCluster` class to meet these needs?

I think a few things would have to change to make the `TestCluster` class more broadly usable:
* Put the class in the `Kafka` module.
* Make the following things configurable:
 * Kafka and Zookeeper images
 * Kafka and Zookeeper logs directory
 * Cluster size (currently hardcoded to 3)
 * Port bindings (currently hardcoded to 9093-9095)
 * Logger (currently a lot of stuff gets logged to stdout)
* Add a timeout waiting for Kafka cluster to startup (currently it will wait indefinitely)
* Add a `delete_topic` method

I'd be happy to do the work if you're interested exposing this capability.

**Comment by dasch** [comment] 2016-05-20 17:33
@jturkel I'm not too interested in having the gem be part of ruby-kafka – but if you extract the code into another gem and make it high quality, I'd love to use it instead of the TestCluster class. Note that currently it's a bit tricky to support multiple versions of Kafka since the topic administration is done via shell scripts executed within the containers. I believe Kafka 0.10 will have proper APIs for admin tasks, but until then there's a rather tight coupling with the container's internals.

**Comment by jturkel** [comment] 2016-05-20 17:34
Sounds reasonable

**Comment by dasch** [comment] 2016-05-20 17:34
Also: I've tried and failed to get the functional tests running in SimpleCI because of some Docker issue. It would be great if you could solve that for the library and maybe test in a few common CI systems (Travis, for instance.)

**Comment by jturkel** [comment] 2016-05-20 17:39
@dasch - Do you have more details on the Docker issues you were seeing?

**Comment by dasch** [comment] 2016-05-20 17:58
Never was able to reproduce it properly, but I think it was related to network settings.

**Comment by jturkel** [comment] 2016-05-20 18:15
Are you guys using SimpleCI or CircleCI? We managed to get our tests running in CircleCI using this fork of the `TestCluster` class: https://gist.github.com/jturkel/44716874997bab8a08911c06638cdcf5. When running in Circle we had to set the `KAFKA_ADVERTISED_HOST_NAME` to:
```
 `/sbin/ifconfig docker0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1`.strip
```

**Comment by dasch** [comment] 2016-05-20 20:56
That worked, thanks!

I'm closing this as it's not really a bug – let me know if you choose to release test-kafka as a gem.

**Closed by dasch** 2016-05-20 20:56 UTC

**Comment by jturkel** [comment] 2016-05-20 21:06
Awesome! Glad you were able to get the tests working in Circle. I'll keep you posted on the gem.
