### ISSUE TITLE
EOFError when the connection was closed by broker because of idle client

### ISSUE THREAD

**Issue by Elyahou** [zendesk/ruby-kafka#395] opened 2017-08-15 21:06 UTC
client connections are being closed by broker after some time, defined by `connections.max.idle.ms` config on the broker (default to 9 min).

I noticed that such closed connections are still being used by ruby-kafka when producing message, and this cause EOFError exceptions, and sync retry after backoff time.

I saw that an attempt to fix this had already been added here https://github.com/zendesk/ruby-kafka/pull/242, but it seems this fix don't work, since the `closed?`return false for these half closed socket.

Maybe the client also need to check this socket expiration and implicitly close the connection when time is expired

**Comment by dasch** [comment] 2017-08-16 09:27
@Elyahou the problem is that the timeout is configurable on the broker side, but we won't know the actual value. I've thought about sending some kind of keep-alive request periodically, but I'm not sure if that's the best solution, as it would add unnecessary traffic.

**Comment by Elyahou** [comment] 2017-08-16 09:29
I know Java client don't have this issue since 0.9 version. Maybe we should
mimic the same behavior as this client ?

**Comment by dasch** [comment] 2017-08-16 09:35
Can you investigate what they're doing in order to avoid the problem? They may do client-side socket cleanup with a lower timeout than the brokers, but I'm not sure if it's bullet-proof.

**Comment by dasch** [comment] 2017-08-25 12:57
Fixed by #399!

**Closed by dasch** 2017-08-25 12:57 UTC
