### ISSUE TITLE
Consumer seeks offsets from previously assigned partitions

### ISSUE THREAD

**Issue by stsc3000** [zendesk/ruby-kafka#611] opened 2018-07-03 07:12 UTC
* Version of Ruby: 2.5.0p0
* Version of Kafka: 0.10.1.0
* Version of ruby-kafka: 0.6.7/master

Hi, I believe we have discovered an issue very similar to the one described in issue #347:

Upon rebalancing within our system, a consumer got assigned a partition that it was assigned previously.
When beginning to consume messages, it then used the offset it previously kept in memory for
the partition to seek, resulting in a lot of duplicate messages being processed.

I believe I have found a way to reproduce the behavior:

### 1. Run Kafka in Docker

`$ docker run --rm --env ADVERTISED_HOST=localhost -p 2181:2181 -p 9092:9092 --env ADVERTISED_PORT=9092 --name kafka -h kafka spotify/kafka`

### 2. Create topic with two partitions

`$ docker exec -it CONTAINER_ID /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh --create --zookeeper localhost:2181 --topic debug-topic --replication-factor 1 --partitions 2`

### 3. Run Consumer 1 (consumer.rb)
* Subscribes to partitions 0 and 1
* Keep running

### 4. Run Producer (producer.rb)
* Consumer 1 receives all messages, sets local offsets

### 5. Run Consumer 2 (consumer.rb, different shell)
* Wait for rebalance
* Each consumer get assigned one partition

### 6. Run Producer (producer.rb)
* Each consumer will receive messages

### 7. Stop Consumer 2
* Wait for rebalance

Assumption: Stopping Consumer 2 does not cause any further processing (as all messages have been already)
Actual Result: Stopping Consumer 2 causes Consumer 1 to process messages that were processed by Consumer 2 already

`consumer.rb`

```ruby
#!/usr/bin/env ruby

require 'ruby-kafka'

TOPIC = 'debug-topic'

logger = Logger.new(STDOUT)
logger.level = Logger::INFO

kafka = Kafka.new(
  seed_brokers: ['localhost:9092'],
  logger: logger
)

consumer = kafka.consumer(group_id: 'consumer-group', offset_commit_threshold: 1)

consumer.subscribe(TOPIC)

consumer.each_message do |msg|
  puts ({ partition: msg.partition, offset: msg.offset }).inspect
end
```

`producer.rb`

```ruby
#!/usr/bin/env ruby

require 'ruby-kafka'

TOPIC = 'debug-topic'

kafka = Kafka.new(seed_brokers: ['localhost:9092'])

producer = kafka.async_producer

20.times do |i|
  producer.produce(i.to_s, topic: TOPIC)
end

producer.deliver_messages
producer.shutdown
```

**Comment by klippx** [comment] 2018-07-03 13:32
Great work! 👍🏼

Spontaneous thought: Can we make a test out of this and add it to the
suite? Sort of an integration test.
tis 3 juli 2018 kl. 09:12 skrev Steffen Schildknecht <
notifications@github.com>:

**Comment by nguyenquangminh0711** [comment] 2018-09-22 03:14
It looks like the issue is fixed in the PR. I'll now close it now. Please feel free to re-open it if this problem still exists.

**Closed by nguyenquangminh0711** 2018-09-22 03:14 UTC
