### ISSUE TITLE
Manual marking of message - low offset override high offset

### ISSUE THREAD

**Issue by pascalmail** [zendesk/ruby-kafka#638] opened 2018-08-31 11:05 UTC
* Version of Ruby: ruby 2.4.1p111 
* Version of Kafka: 1.1.0
* Version of ruby-kafka: 0.7.1.beta1 (master@d57e6db)

When manually marking message, marking message with offset lower than previously marked offset overwrites the higher offset with the lower one.
Is this the intended behaviour?

###### Steps to reproduce

```ruby
require 'kafka'

brokers = ['127.0.0.1:9092']
topic = 'marking'
group_id = 'SSD'

client = Kafka.new(brokers)
client.delete_topic(topic) rescue nil

producer = client.producer
(1..4).each do |i|
  puts "Produce: msg#{i}"
  producer.produce("msg#{i}", topic: topic)
  producer.deliver_messages
end

consumer = client.consumer(group_id: group_id)
consumer.subscribe(topic)

# Queue is accessed by some worker pool
q = SizedQueue.new(10)
thr = Thread.new do
   consumer.each_message(automatically_mark_as_processed: false) do |msg|
      puts "Offset:#{msg.offset} - Value:#{msg.value}\n"
      q.push(msg)
   end
end

m = Array.new(4) { q.pop }

# Some race condition made the marking not ordered
puts "Marking offset #{m[2].offset} as processed"
consumer.mark_message_as_processed(m[2])
puts "Marking offset #{m[0].offset} as processed"
consumer.mark_message_as_processed(m[0])

consumer.commit_offsets
consumer.stop

puts 'New consumer...'
consumer2 = client.consumer(group_id: group_id)
consumer2.subscribe(topic)

trap('TERM') { consumer2.stop }

consumer2.each_message do |msg|
  puts "Offset:#{msg.offset} - Value:#{msg.value}\n"
end
```

###### Expected outcome
```
Produce: msg1
Produce: msg2
Produce: msg3
Produce: msg4
Offset:0 - Value:msg1
Offset:1 - Value:msg2
Offset:2 - Value:msg3
Offset:3 - Value:msg4
Marking offset 2 as processed
Marking offset 0 as processed
New consumer
Offset:3 - Value:msg4
```
###### Actual outcome
```
Produce: msg1
Produce: msg2
Produce: msg3
Produce: msg4
Offset:0 - Value:msg1
Offset:1 - Value:msg2
Offset:2 - Value:msg3
Offset:3 - Value:msg4
Marking offset 2 as processed
Marking offset 0 as processed
New consumer
Offset:1 - Value:msg2
Offset:2 - Value:msg3
Offset:3 - Value:msg4
```

**Comment by nguyenquangminh0711** [comment] 2018-09-01 08:08
@pascalmail I think this is not a bug to me. The offset is replaced when you call `mark_message_as_processed` before committing offset to Kafka. In almost cases, the messages from a same partition are handled in order; after a message is consumed, it is marked as processed and offsets are committed to Kafka. If you turn off automatically_mark_as_processed option, you'll have to take a risk and handle the offsets by yourself.

**Comment by nguyenquangminh0711** [comment] 2018-09-20 11:29
@pascalmail I will close this issue due to the lack of activities. Feel free to re-open it if you need anything else related to this issue.

**Closed by nguyenquangminh0711** 2018-09-20 11:29 UTC
