### ISSUE TITLE
Kafka::ConnectionError: Could not connect to any of the seed brokers

### ISSUE THREAD

**Issue by umeshshimpi** [zendesk/ruby-kafka#672] opened 2018-10-18 21:28 UTC
If this is a bug report, please fill out the following:

* Version of Ruby: 2.5.1
* Version of Kafka: 0.10
* Version of ruby-kafka: 0.7.3

I am trying to use `ruby-kafka` client and I have made following changes.

###### Steps to reproduce

```ruby
kafka = Kafka.new(["abc123d.xyz.cde.net:9093",
                       "abc123f.xyz.cde.net:9093",
                       "abc123h.xyz.cde.net:9093",
                       "abc123k.xyz.cde.net:9093"
                     ],
                     logger: Rails.logger)
    kafka.deliver_message("Hello, World!", topic: "SomeTopic")

```
I am getting error:

```
Kafka::ConnectionError: Could not connect to any of the seed brokers:
- kafka://abc123d.xyz.cde.net:9093: Connection error EOFError: EOFError
- kafka://abc123f.xyz.cde.net:9093: Connection error EOFError: EOFError
- kafka://abc123h.xyz.cde.net:9093: Connection error EOFError: EOFError
- kafka://abc123k.xyz.cde.net:9093: Connection error EOFError: EOFError

```

I am able to see topics when i do `kafka.topics`

I checked many posts on github about same issue but can't find a proper answer to this.

Does anyone know how to fix this?

**Comment by nguyenquangminh0711** [comment] 2018-10-19 07:08
@umeshshimpi Are you sure that the brokers are correct, or connectable from your machine, or have  any kinds of authentication? Does it work with other clients?

**Comment by umeshshimpi** [comment] 2018-10-19 12:40
yes if i do `nc -z abc123d.xyz.cde.net 9093` I am able to connect to broker successfully from my machine. There is a kerberos authentication required to connect to kafka but since i can connect from machine, i should be able to using `ruby-kafka` right? We are first time using kafka.

**Comment by nguyenquangminh0711** [comment] 2018-10-20 07:18
Hi @umeshshimpi, the original error comes from the lack of authentication, in your case gssapi authentication. Can you add `gssapi` into your Gemfile, bundle and try again?

**Comment by umeshshimpi** [comment] 2018-10-20 15:45
@nguyenquangminh0711 Yes i added the gssapi in my gemfile and it works but still facing error `could not connect to broker Could not connect to broker abc123f.xyz.cde.net:9093 Connection error EOFError: EOFError`

**Comment by umeshshimpi** [comment] 2018-10-22 19:36
@nguyenquangminh0711 When I lowered the ruby-kafka version to 0.6.8 it started working.

**Comment by nguyenquangminh0711** [comment] 2018-10-25 17:29
Oh right. I didn't realize that you are using Kafka 0.10. From version 0.7.x, the support for Kafka 0.10 is dropped, in the replacement of new Record Batch format in kafka 0.11. So, please use 0.6.x branches, or upgrade your kafka version.

**Comment by nguyenquangminh0711** [comment] 2018-10-30 17:01
So, in case the issue is resolved, I'll close this pull request. Post action of this issue: update the compatibility metrics.

**Closed by nguyenquangminh0711** 2018-10-30 17:01 UTC

**Comment by dorianmarie** [comment] 2023-08-09 14:48
I needed to start zookeeper, e.g. `brew services restart zookeeper`
