### ISSUE TITLE
consumer group question

### ISSUE THREAD

**Issue by tslcjames** [zendesk/ruby-kafka#215] opened 2016-06-10 09:45 UTC
I am using the consumer group and have a wired random problem
let's how I use , and I have 3 broker, and use two process to run 2 consumer, topic has 100 partitions
```
client_consumer = Kafka.new(seed_brokers: ['localhost:9092', 'localhost:9093', 'localhost:9094'])

consumer = client_consumer.consumer(group_id: "group_tet", offset_commit_interval: 0])
consumer.subscribe('test_topic', default_offset: :latest)} 
consumer.each_message do |message|
  do_jobs(message)
end
```

but sometime the message will lost, and just lost some partition message
see the log like this
`Resolving offset `-1` for test_topic/0...`
`Offset for test_topic/0 is 30`

and after I produce more message to partition 0, still no message comes out to each_message
but the log offset will increase like this, and keep increase 
`Resolving offset `-1` for test_topic/0...`
`Offset for test_topic/0 is 31`

so I think is there some issue here?
https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/fetch_operation.rb#L101

when got the offset here
`resolved_offset = response.offset_for(topic, partition)
topics[topic][partition][:fetch_offset] = resolved_offset || 0`
is it already the latest offset?, use it to do following step will return nothing to each_message

the difficult of this problem is I can't find the consistent reproduce method....
thanks for help

**Comment by dasch** [comment] 2016-06-10 17:34
Try setting `offset_commit_interval` to 1 rather than 0.

**Comment by dasch** [comment] 2016-06-10 17:39
Also: `Resolving offset-1for test_topic/0...` probably means that the offset for that partition has not been committed at all, or that the commit has expired. Do you stop the jobs and restart them much later? The client uses the default commit retention time configured in the broker, so after a while the commit will be removed.

**Comment by tslcjames** [comment] 2016-06-11 02:58
thanks for your reply~
1. I try to set `offset_commit_interval ` to 1 before, but more than 1 message will comes in 1s from different partitions and only the first message will commit and other message from different partition wii not commit. Therefore I set to 0.

2. for this `Resolving offset `-1` for test_topic/0...`. I think it's ok to get -1 here
because the following will work and get the offset for this topic, partition
https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/fetch_operation.rb#L124
log like this `Offset for test_topic/0 is 30`
but the problem might be, if the offset already 30, use 30 to consume this partition will not receive any new message, but actually consumer didn't consume offset 30 or 29 yet.

thanks

**Comment by dasch** [comment] 2016-06-13 20:15
I'm not quite sure I understand the problem here. If `do_jobs()` in your example works _synchronously_ you should _not_ see any message loss. Are you using threads to do processing?

**Comment by tslcjames** [comment] 2016-06-14 07:42
it's not related to the do_jobs(), even I put logs here, it didn't show up when issue happened
```
consumer.each_message do |message|
  puts "topic=#{message.topic}, partition=#{message.partition}, offset=#{message.offset}"
  do_jobs(message)
end
```

the problem is the consumer can't receive message from some partitions
this normal partition
Fetching batch from test_topic/2 starting at offset 3
this is abnormal
Fetching batch from test_topic/14 starting at offset latest

it's that more clear@@?I'm sorry that I still not found the reproduce steps
all I know is start the consumer and stay for 1 day, it might happen

**Comment by tslcjames** [comment] 2016-06-14 11:39
sorry, more clear information now,
```
client_consumer = Kafka.new(seed_brokers: ['localhost:9092', 'localhost:9093', 'localhost:9094'])

consumer = client_consumer.consumer(group_id: "group_tet", offset_commit_interval: 0])
consumer.subscribe('test_topic_1', default_offset: :latest)
consumer.subscribe('test_topic_2', default_offset: :latest)
consumer.subscribe('test_topic_3', default_offset: :latest) 
consumer.each_message do |message|
  do_jobs(message)
end
```
we subscribe 3 topic in one consumer, 
when I only subscribe to 1 topic, it looks fine (I'm not sure , because the issue is random)

I saw the code here, looks like the offset manager is same one
https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L75
so...could we subscribe to 3 topic in one consumer?

thanks

**Comment by dasch** [comment] 2016-06-14 20:59
First of all, `offset_commit_interval: 0` is simply wrong – that's _not_ how you want to trigger offset commits. If you want offsets committed after every single message processing, use `offset_commit_threshold: 1`.

> Fetching batch from test_topic/14 starting at offset latest

This simply means that no offsets have been committed for that partition yet, so the client will wait for messages to appear at the end of the partition. Note that since you set `default_offset: :latest`, you will have message loss _by design_. The client will wait for _new_ messages to appear in the partitions but will not look at previous messages. You should consider using `:earliest` instead, which is the default.

**Comment by dasch** [comment] 2016-06-14 20:59
Also: are you sure that you're writing messages to all partitions? What's your partitioning key?

**Comment by tslcjames** [comment] 2016-06-15 16:08
yes I'm sure the producer successfully add message into different partitions
I using simple consumer to make sure that

and I change to `default_offset: :earliest` and the issue disappear 
but the different between `:latest` and `earliest` only is the first time consuming position
I still can't understand why using `:latest`, the messages from some partition can't be consumed but other partition is fine

thanks

**Comment by dasch** [comment] 2016-06-15 16:14
When using `:latest`, only messages written to the partition *after* the consumer starts will be consumed. It's not enough that there are already messages in the partition.

**Comment by dasch** [comment] 2016-06-15 16:15
If you can provide a full script that both produces and consumes and exhibits this problem, then I would be able to debug it.

**Comment by tslcjames** [comment] 2016-06-19 13:24
here is the reproduce steps
1. clean all data in kafka broker and zookeeper 
2. restart server and create 3 topics(replication factor 2, partition 2)
3. start consumer 
```
client_consumer = Kafka.new(seed_brokers: ['localhost:9092', 'localhost:9093', 'localhost:9094'])

consumer = client_consumer.consumer(group_id: "group_tet", offset_commit_threshold: 0])
consumer.subscribe('test_topic_1', default_offset: :latest)} 
consumer.subscribe('test_topic_2', default_offset: :latest)} 
consumer.subscribe('test_topic_3', default_offset: :latest)} 
consumer.each_message do |message|
  do_jobs(message)
end
```
produce message to each partition periodically
```
producer = kafka.async_producer(delivery_threshold: 10, delivery_interval: 10)
producer.produce(data, topic: topic, partition: partition)
```

thanks

**Comment by dasch** [comment] 2016-06-20 23:05
Okay, I think I've found the issue – there's a race condition when the consumer subscribes to the latest messages. If no messages arrive in the `max_wait_time` window (which can be passed to `#each_consumer`) the consumer will try another fetch, but since it has no committed offsets for the partitions it will try to resolve the `:latest` offset again, which might mean skipping some messages that have arrived in the interim.

I think the correct solution would be to resolve offsets for all partitions at consumer startup.

**Comment by tslcjames** [comment] 2016-06-21 14:04
thanks for your help
I will try after you fix, thanks

**Comment by dasch** [comment] 2016-06-23 21:27
@tslcjames can you verify that #230 fixes your problem?

**Comment by tslcjames** [comment] 2016-06-24 09:10
@dasch  thanks for your fix
I Use this version to test
`gem 'ruby-kafka', git: 'https://github.com/zendesk/ruby-kafka.git', ref: 'ecdf17e37ea296bd8614cbd1a909ef6ad8c94e92'`

when I delete all data in kafka server and restart broker and consumer
The exception `Kafka::OffsetOutOfRange` will happen
after I create one message to each partition, the situation disappear
and the issue I mentioned before also fixed, consumer could receive all message from each partition

I saw the log when the consumer start before any message produce
```
Fetching batch from test-topic-1/1 starting at offset 1
Fetching batch from test-topic-1/0 starting at offset 1
Fetching batch from test-topic-2/1 starting at offset 1
Fetching batch from test-topic-2/0 starting at offset 1
Fetching batch from test-topic-3/1 starting at offset 1
Fetching batch from test-topic-3/0 starting at offset 1
```
looks like the offset is wrong? there is no message in any topic now, but the offset already is 1

thanks for your help

**Comment by dasch** [comment] 2016-06-24 17:15
Hmm, let me check up on that.

**Comment by dasch** [comment] 2016-06-24 17:26
@tslcjames can you try with the latest HEAD of the branch again?

**Comment by tslcjames** [comment] 2016-06-25 00:21
@dasch yes! it look nice! now the offset is correct and all partition message received
`gem 'ruby-kafka', git: 'https://github.com/zendesk/ruby-kafka.git', ref: '8b53cf9935020e4eb234581eca8b09f053055fea'`

the other question, as I mentioned before
whether there is same problem in here `resolve_offsets`?
https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/fetch_operation.rb#L101

thanks

**Comment by dasch** [comment] 2016-06-25 00:35
Awesome! I'll merge that PR, then.

I don't think the problem applies to the fetch operation – Kafka's offset handling is a bit weird, here. Basically, when fetching you provide the _starting offset_ of the fetch, so when tailing the topic you specify the offset of the next message to be written. The problem with the PR was that I tried to _commit_ the next offset rather than the current one.

**Closed** 2016-06-25 00:36 UTC
Labels: bug

**Comment by tslcjames** [comment] 2016-06-27 06:09
@dasch 
I think I forget to test `earliest` case, this modification need to consider `earliest` also
https://github.com/zendesk/ruby-kafka/blob/51c7b83b327089aa9fd9bb488340176c2bfe608d/lib/kafka/cluster.rb#L136

thanks

**Comment by dasch** [comment] 2016-06-27 08:31
I thought that would just work, since resolving `earliest` _should_ return the actual offset of the earliest message. Have you observed a problem?

**Comment by tslcjames** [comment] 2016-06-27 09:38
Yes, same offset out of range situation when first start, have you seen that before?

**Comment by dasch** [comment] 2016-06-27 11:01
Hmm. It's probably because those offsets don't exist in the partitions.

**Comment by dasch** [comment] 2016-06-27 11:30
@tslcjames can you test out https://github.com/zendesk/ruby-kafka/pull/231 for me?

**Comment by tslcjames** [comment] 2016-06-28 08:12
@dasch I tested with `:latest` and `:earliest` , it ok with this version
`3b27512a025d5559f040d6c389dddfddac479515`

the other question, I saw sometimes the offset will be `-1` when get the committed offset
even though I didn't start a new consumer group, 
https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/offset_manager.rb#L32
what's the other scenario when saw `-1` here?

thanks

**Comment by dasch** [comment] 2016-06-28 08:20
If the offset list API returns -1 it means no offset has been committed, or that the offset commit has expired. If your consumer group is inactive for a long period of time the commits may expire.

**Comment by tslcjames** [comment] 2016-06-28 16:36
I see, I found it's the offsets.retention.minutes too low, so the offset will be clear
thanks

**Comment by dasch** [comment] 2016-06-28 17:14
It's possible to override that default in the client, but I'm not exposing it as an option yet. I've added #233 to track the issue.
