### ISSUE TITLE
"conversion of nil into Integer (TypeError)" on response from leave group API request

### ISSUE THREAD

**Issue by awseward** [zendesk/ruby-kafka#623] opened 2018-07-30 21:32 UTC
* Version of Ruby: 2.2.9p480
* Version of Kafka: 1.0.1
* Version of ruby-kafka: 0.6.6

Hey there, we're seeing an issue that appears to be tied to particular consumer groups.
It looks like the consumer is having issues with a response from a leave group request.

Moving the consumer to a new consumer group resolves the issue, but then going back to the original consumer group brings the error right back.

Also, destroying, then recreating, the consumer group on the brokers does not resolve the issue.

Worth noting is that we're only seeing this on our staging clusters (running Kafka v1.0.1) so it may be an issue of what this gem will or won't support..

We've got a separate effort underway to get the Kafka version on our staging cluster more in line w/ our prod cluster, but I figured it was worth reaching out in the meantime, does anything jump out as a potential cause we could investigate further?

```
D, [2018-07-30T17:31:14.675289 #1] DEBUG -- : Closing socket to ...
D, [2018-07-30T17:31:14.675598 #1] DEBUG -- : Opening connection to ...
D, [2018-07-30T17:31:14.931551 #1] DEBUG -- : Sending fetch API request 1 to ...
I, [2018-07-30T17:31:14.932403 #1]  INFO -- : Leaving group ...
D, [2018-07-30T17:31:14.932648 #1] DEBUG -- : Sending leave_group API request 5 to ...
D, [2018-07-30T17:31:14.932834 #1] DEBUG -- : Waiting for response 5 from ...
D, [2018-07-30T17:31:15.007104 #1] DEBUG -- : Received response 5 from ...
E, [2018-07-30T17:31:15.007505 #1] ERROR -- : no implicit conversion of nil into Integer
E, [2018-07-30T17:31:15.007575 #1] ERROR -- : /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:59:in `pack'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:59:in `write_int32'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/fetch_request.rb:59:in `block (2 levels) in encode'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:84:in `each'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:84:in `write_array'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/fetch_request.rb:53:in `block in encode'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:84:in `each'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:84:in `write_array'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/fetch_request.rb:50:in `encode'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/request_message.rb:22:in `encode'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:122:in `encode_with'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/connection.rb:162:in `write_request'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/connection.rb:103:in `block in send_request'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/connection.rb:96:in `send_request'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/broker.rb:170:in `send_request'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/broker.rb:54:in `fetch_messages'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetch_operation.rb:76:in `block in execute'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetch_operation.rb:66:in `each'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetch_operation.rb:66:in `flat_map'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetch_operation.rb:66:in `execute'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetcher.rb:174:in `fetch_batches'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetcher.rb:130:in `step'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetcher.rb:92:in `loop'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetcher.rb:32:in `block in initialize'
/usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:59:in `pack': no implicit conversion of nil into Integer (TypeError)
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:59:in `write_int32'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/fetch_request.rb:59:in `block (2 levels) in encode'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:84:in `each'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:84:in `write_array'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/fetch_request.rb:53:in `block in encode'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:84:in `each'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:84:in `write_array'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/fetch_request.rb:50:in `encode'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/request_message.rb:22:in `encode'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/protocol/encoder.rb:122:in `encode_with'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/connection.rb:162:in `write_request'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/connection.rb:103:in `block in send_request'
        from /usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `block in instrument'
        from /usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
        from /usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/notifications.rb:166:in `instrument'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/instrumenter.rb:21:in `instrument'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/connection.rb:96:in `send_request'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/broker.rb:170:in `send_request'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/broker.rb:54:in `fetch_messages'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetch_operation.rb:76:in `block in execute'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetch_operation.rb:66:in `each'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetch_operation.rb:66:in `flat_map'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetch_operation.rb:66:in `execute'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetcher.rb:174:in `fetch_batches'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetcher.rb:130:in `step'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetcher.rb:92:in `loop'
        from /usr/local/bundle/gems/ruby-kafka-0.6.6/lib/kafka/fetcher.rb:32:in `block in initialize'
```

**Comment by dasch** [comment] 2018-08-07 11:50
Looks like a change in the API.

**Comment by dasch** [comment] 2018-09-20 09:34
@nguyenquangminh0711 would you have time to look into this?

**Comment by nguyenquangminh0711** [comment] 2018-09-23 08:31
The direct cause is because the max bytes per partition option is nil. The only root cause I could think of that leads to this situation is because the server responds an empty message set (converted from record batch), and mess up the states of the fetcher. If that assumption is right, we just need not to update the fetcher state when the fetched batch is empty; which is already fixed in https://github.com/zendesk/ruby-kafka/pull/625/files. 

So, @awseward, if it's possible, please update to the newest stable version (0.6.8) to see whether this problem is gone or not.

**Comment by nguyenquangminh0711** [comment] 2018-10-06 08:51
I'll close this issue due to the lack of activities, and I think this issue is fixed. Please feel free to re-open it again.

**Closed by nguyenquangminh0711** 2018-10-06 08:51 UTC
Labels: bug

**Comment by sittitep** [comment] 2018-12-25 05:06
I'm still getting this error on ruby-kafka (0.7.4)

**Comment by fcce** [comment] 2019-01-10 09:40
getting this error on ruby-kafka (0.7.4).
```ruby
TypeError: no implicit conversion of nil into Integer
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/protocol/encoder.rb:57:in `pack'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/protocol/encoder.rb:57:in `write_int32'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/protocol/fetch_request.rb:64:in `block (2 levels) in encode'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/protocol/encoder.rb:82:in `each'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/protocol/encoder.rb:82:in `write_array'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/protocol/fetch_request.rb:58:in `block in encode'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/protocol/encoder.rb:82:in `each'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/protocol/encoder.rb:82:in `write_array'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/protocol/fetch_request.rb:55:in `encode'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/protocol/request_message.rb:22:in `encode'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/protocol/encoder.rb:178:in `encode_with'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/connection.rb:162:in `write_request'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/connection.rb:103:in `block in send_request'
ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/notifications.rb:168:in `instrument'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/instrumenter.rb:21:in `instrument'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/connection.rb:96:in `send_request'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/broker.rb:188:in `send_request'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/broker.rb:54:in `fetch_messages'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/fetch_operation.rb:81:in `block in execute'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/fetch_operation.rb:71:in `each'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/fetch_operation.rb:71:in `flat_map'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/fetch_operation.rb:71:in `execute'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/fetcher.rb:197:in `fetch_batches'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/fetcher.rb:153:in `step'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/fetcher.rb:109:in `loop'
ruby/2.3.0/gems/ruby-kafka-0.7.4/lib/kafka/fetcher.rb:54:in `block in start'
```

**Comment by mensfeld** [comment] 2019-01-10 09:47
Could you try this release? https://rubygems.org/gems/ruby-kafka/versions/0.7.5.beta1

**Comment by fcce** [comment] 2019-01-11 03:36
@mensfeld The same problem
```ruby
TypeError: no implicit conversion of nil into Integer
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:57:in `pack'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:57:in `write_int32'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/fetch_request.rb:64:in `block (2 levels) in encode'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:82:in `each'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:82:in `write_array'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/fetch_request.rb:58:in `block in encode'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:82:in `each'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:82:in `write_array'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/fetch_request.rb:55:in `encode'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/request_message.rb:22:in `encode'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:178:in `encode_with'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/connection.rb:162:in `write_request'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/connection.rb:103:in `block in send_request'
ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/notifications.rb:168:in `instrument'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/instrumenter.rb:21:in `instrument'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/connection.rb:96:in `send_request'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/broker.rb:188:in `send_request'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/broker.rb:54:in `fetch_messages'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetch_operation.rb:81:in `block in execute'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetch_operation.rb:71:in `each'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetch_operation.rb:71:in `flat_map'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetch_operation.rb:71:in `execute'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetcher.rb:198:in `fetch_batches'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetcher.rb:154:in `step'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetcher.rb:110:in `loop'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetcher.rb:56:in `block in start'
```
I use the [racecar](https://github.com/zendesk/racecar) gem,It's happened, when start two different consumer 

```ruby
bundle exec racecar AConsumer
bundle exec racecar BConsumer
```

**Comment by pamellatater** [comment] 2019-01-26 20:39
I'm still getting this error on ruby-kafka (0.7.4)

TypeError: no implicit conversion of nil into Integer
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:57:in `pack'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:57:in `write_int32'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/fetch_request.rb:64:in `block (2 levels) in encode'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:82:in `each'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:82:in `write_array'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/fetch_request.rb:58:in `block in encode'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:82:in `each'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:82:in `write_array'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/fetch_request.rb:55:in `encode'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/request_message.rb:22:in `encode'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/protocol/encoder.rb:178:in `encode_with'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/connection.rb:162:in `write_request'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/connection.rb:103:in `block in send_request'
ruby/2.3.0/gems/activesupport-5.1.0/lib/active_support/notifications.rb:168:in `instrument'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/instrumenter.rb:21:in `instrument'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/connection.rb:96:in `send_request'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/broker.rb:188:in `send_request'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/broker.rb:54:in `fetch_messages'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetch_operation.rb:81:in `block in execute'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetch_operation.rb:71:in `each'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetch_operation.rb:71:in `flat_map'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetch_operation.rb:71:in `execute'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetcher.rb:198:in `fetch_batches'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetcher.rb:154:in `step'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetcher.rb:110:in `loop'
ruby/2.3.0/gems/ruby-kafka-0.7.5.beta1/lib/kafka/fetcher.rb:56:in `block in start'

**Comment by fcce** [comment] 2019-03-05 04:48
@mensfeld  For my case, It's not a bug of  ruby-kafka. It's my fault. I set the same `group_id` to different [Racecar](https://github.com/zendesk/racecar) Consumer class. @pamellatater , maybe you can check your settings.

**Comment by bruiiser** [comment] 2019-06-14 21:38
Having just updated my ruby-kafka gem to 0.7.7, I'm experiencing a similar issue:

`#<Thread:0x000055a2685673d0@/opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:54 run> terminated with exception (report_on_exception is true):
/opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:57:in `pack': no implicit conversion of nil into Integer (TypeError)
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:57:in `write_int32'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/fetch_request.rb:64:in `block (2 levels) in encode'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `each'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `write_array'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/fetch_request.rb:58:in `block in encode'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `each'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `write_array'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/fetch_request.rb:55:in `encode'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/request_message.rb:22:in `encode'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:178:in `encode_with'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/connection.rb:165:in `write_request'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/connection.rb:104:in `block in send_request'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:166:in `instrument'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/instrumenter.rb:21:in `instrument'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/connection.rb:97:in `send_request'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/broker.rb:200:in `send_request'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/broker.rb:54:in `fetch_messages'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:81:in `block in execute'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:71:in `each'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:71:in `flat_map'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:71:in `execute'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:201:in `fetch_batches'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:157:in `step'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:111:in `loop'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:56:in `block in start'
rake aborted!
TypeError: no implicit conversion of nil into Integer`

**Comment by bruiiser** [comment] 2019-06-15 04:02
Having just updated my ruby-kafka gem to 0.7.7, I'm experiencing a similar issue:

`#<Thread:0x000055a2685673d0@/opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:54 run> terminated with exception (report_on_exception is true):
/opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:57:in `pack': no implicit conversion of nil into Integer (TypeError)
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:57:in `write_int32'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/fetch_request.rb:64:in `block (2 levels) in encode'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `each'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `write_array'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/fetch_request.rb:58:in `block in encode'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `each'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:82:in `write_array'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/fetch_request.rb:55:in `encode'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/request_message.rb:22:in `encode'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/protocol/encoder.rb:178:in `encode_with'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/connection.rb:165:in `write_request'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/connection.rb:104:in `block in send_request'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.2/lib/active_support/notifications.rb:166:in `instrument'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/instrumenter.rb:21:in `instrument'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/connection.rb:97:in `send_request'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/broker.rb:200:in `send_request'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/broker.rb:54:in `fetch_messages'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:81:in `block in execute'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:71:in `each'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:71:in `flat_map'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetch_operation.rb:71:in `execute'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:201:in `fetch_batches'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:157:in `step'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:111:in `loop'
        from /opt/rubies/ruby-2.5.3/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.7/lib/kafka/fetcher.rb:56:in `block in start'
rake aborted!
TypeError: no implicit conversion of nil into Integer`

**Comment by stsmurf** [comment] 2019-07-09 22:29
I did the same as @fcce 
This error shows up if you try to setup 2 consumers with the same `group_id` but do NOT have the same topic subscribed on both.
