### ISSUE TITLE
Processing error causes Kafka to exit the fetcher thread

### ISSUE THREAD

**Issue by mensfeld** [zendesk/ruby-kafka#686] opened 2018-11-15 10:48 UTC
* Version of Ruby: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]`
* Version of Kafka: `1.0.1`
* Version of ruby-kafka: `0.7.4`

Does **NOT** happen for `0.7.2`. It does happen for `0.7.3` as well.

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka:

it is not fixed.

###### Steps to reproduce

```ruby
require 'kafka'

logger = Logger.new(STDOUT)

kafka = Kafka.new(
  ['localhost:9092'],
  logger: logger
)

10.times do |i|
  kafka.deliver_message("Hello, World! #{i}", topic: 'test')
end

consumer = kafka.consumer(group_id: 'test')

consumer.subscribe('test')

begin
  consumer.each_message do |message|
    puts message.offset, message.key, message.value
    raise StandardError
  end
rescue Kafka::ProcessingError => e
  p e
  retry
end
```

###### Expected outcome

It is expected to retry the processing.

###### Actual outcome

`Fetcher thread exited` - it stops fetching messages and no batches to process.

```
I, [2018-11-15T11:45:44.858521 #31649]  INFO -- : New topics added to target list: test
I, [2018-11-15T11:45:44.858569 #31649]  INFO -- : Fetching cluster metadata from kafka://172.20.24.239:9092
D, [2018-11-15T11:45:44.858604 #31649] DEBUG -- : Opening connection to 172.20.24.239:9092 with client id ruby-kafka...
D, [2018-11-15T11:45:44.858805 #31649] DEBUG -- : Sending topic_metadata API request 1 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.858898 #31649] DEBUG -- : Waiting for response 1 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.859832 #31649] DEBUG -- : Received response 1 from 172.20.24.239:9092
I, [2018-11-15T11:45:44.859867 #31649]  INFO -- : Discovered cluster metadata; nodes: 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.859885 #31649] DEBUG -- : Closing socket to 172.20.24.239:9092
D, [2018-11-15T11:45:44.860005 #31649] DEBUG -- : Current leader for test/0 is node 172.20.24.239:9092 (node_id=1001)
I, [2018-11-15T11:45:44.860033 #31649]  INFO -- : Sending 1 messages to 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.860073 #31649] DEBUG -- : Opening connection to 172.20.24.239:9092 with client id ruby-kafka...
D, [2018-11-15T11:45:44.860190 #31649] DEBUG -- : Sending produce API request 1 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.860593 #31649] DEBUG -- : Waiting for response 1 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.861460 #31649] DEBUG -- : Received response 1 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.861498 #31649] DEBUG -- : Successfully appended 1 messages to test/0 on 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.861573 #31649] DEBUG -- : Current leader for test/0 is node 172.20.24.239:9092 (node_id=1001)
I, [2018-11-15T11:45:44.861596 #31649]  INFO -- : Sending 1 messages to 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.861631 #31649] DEBUG -- : Sending produce API request 2 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.861739 #31649] DEBUG -- : Waiting for response 2 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.862466 #31649] DEBUG -- : Received response 2 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.862495 #31649] DEBUG -- : Successfully appended 1 messages to test/0 on 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.862548 #31649] DEBUG -- : Current leader for test/0 is node 172.20.24.239:9092 (node_id=1001)
I, [2018-11-15T11:45:44.862586 #31649]  INFO -- : Sending 1 messages to 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.862615 #31649] DEBUG -- : Sending produce API request 3 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.862713 #31649] DEBUG -- : Waiting for response 3 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.863370 #31649] DEBUG -- : Received response 3 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.863399 #31649] DEBUG -- : Successfully appended 1 messages to test/0 on 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.863455 #31649] DEBUG -- : Current leader for test/0 is node 172.20.24.239:9092 (node_id=1001)
I, [2018-11-15T11:45:44.863475 #31649]  INFO -- : Sending 1 messages to 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.863504 #31649] DEBUG -- : Sending produce API request 4 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.863605 #31649] DEBUG -- : Waiting for response 4 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.864287 #31649] DEBUG -- : Received response 4 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.864323 #31649] DEBUG -- : Successfully appended 1 messages to test/0 on 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.864382 #31649] DEBUG -- : Current leader for test/0 is node 172.20.24.239:9092 (node_id=1001)
I, [2018-11-15T11:45:44.864403 #31649]  INFO -- : Sending 1 messages to 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.864434 #31649] DEBUG -- : Sending produce API request 5 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.864537 #31649] DEBUG -- : Waiting for response 5 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.865169 #31649] DEBUG -- : Received response 5 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.865208 #31649] DEBUG -- : Successfully appended 1 messages to test/0 on 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.865280 #31649] DEBUG -- : Current leader for test/0 is node 172.20.24.239:9092 (node_id=1001)
I, [2018-11-15T11:45:44.865302 #31649]  INFO -- : Sending 1 messages to 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.865328 #31649] DEBUG -- : Sending produce API request 6 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.865431 #31649] DEBUG -- : Waiting for response 6 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.866069 #31649] DEBUG -- : Received response 6 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.866108 #31649] DEBUG -- : Successfully appended 1 messages to test/0 on 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.866165 #31649] DEBUG -- : Current leader for test/0 is node 172.20.24.239:9092 (node_id=1001)
I, [2018-11-15T11:45:44.866189 #31649]  INFO -- : Sending 1 messages to 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.866218 #31649] DEBUG -- : Sending produce API request 7 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.866342 #31649] DEBUG -- : Waiting for response 7 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.867013 #31649] DEBUG -- : Received response 7 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.867052 #31649] DEBUG -- : Successfully appended 1 messages to test/0 on 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.867113 #31649] DEBUG -- : Current leader for test/0 is node 172.20.24.239:9092 (node_id=1001)
I, [2018-11-15T11:45:44.867135 #31649]  INFO -- : Sending 1 messages to 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.867162 #31649] DEBUG -- : Sending produce API request 8 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.867265 #31649] DEBUG -- : Waiting for response 8 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.867847 #31649] DEBUG -- : Received response 8 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.867884 #31649] DEBUG -- : Successfully appended 1 messages to test/0 on 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.867977 #31649] DEBUG -- : Current leader for test/0 is node 172.20.24.239:9092 (node_id=1001)
I, [2018-11-15T11:45:44.867998 #31649]  INFO -- : Sending 1 messages to 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.868026 #31649] DEBUG -- : Sending produce API request 9 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.868127 #31649] DEBUG -- : Waiting for response 9 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.868773 #31649] DEBUG -- : Received response 9 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.868812 #31649] DEBUG -- : Successfully appended 1 messages to test/0 on 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.868870 #31649] DEBUG -- : Current leader for test/0 is node 172.20.24.239:9092 (node_id=1001)
I, [2018-11-15T11:45:44.868890 #31649]  INFO -- : Sending 1 messages to 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.868920 #31649] DEBUG -- : Sending produce API request 10 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.869025 #31649] DEBUG -- : Waiting for response 10 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.869645 #31649] DEBUG -- : Received response 10 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.869678 #31649] DEBUG -- : Successfully appended 1 messages to test/0 on 172.20.24.239:9092 (node_id=1001)
I, [2018-11-15T11:45:44.869755 #31649]  INFO -- : New topics added to target list: test
I, [2018-11-15T11:45:44.869779 #31649]  INFO -- : Fetching cluster metadata from kafka://172.20.24.239:9092
D, [2018-11-15T11:45:44.869810 #31649] DEBUG -- : Opening connection to 172.20.24.239:9092 with client id ruby-kafka...
D, [2018-11-15T11:45:44.869941 #31649] DEBUG -- : Sending topic_metadata API request 1 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.870009 #31649] DEBUG -- : Waiting for response 1 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.870642 #31649] DEBUG -- : Received response 1 from 172.20.24.239:9092
I, [2018-11-15T11:45:44.870674 #31649]  INFO -- : Discovered cluster metadata; nodes: 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.870693 #31649] DEBUG -- : Closing socket to 172.20.24.239:9092
I, [2018-11-15T11:45:44.870810 #31649]  INFO -- : Joining group `test`
D, [2018-11-15T11:45:44.870837 #31649] DEBUG -- : Getting group coordinator for `test`
D, [2018-11-15T11:45:44.870900 #31649] DEBUG -- : Handling fetcher command: subscribe
I, [2018-11-15T11:45:44.871018 #31649]  INFO -- : Will fetch at most 1048576 bytes at a time per partition from test
D, [2018-11-15T11:45:44.871046 #31649] DEBUG -- : Handling fetcher command: configure
D, [2018-11-15T11:45:44.871084 #31649] DEBUG -- : Fetching batches
I, [2018-11-15T11:45:44.871127 #31649]  INFO -- : Fetching cluster metadata from kafka://172.20.24.239:9092
D, [2018-11-15T11:45:44.871165 #31649] DEBUG -- : Opening connection to 172.20.24.239:9092 with client id ruby-kafka...
D, [2018-11-15T11:45:44.870949 #31649] DEBUG -- : Opening connection to 172.20.24.239:9092 with client id ruby-kafka...
D, [2018-11-15T11:45:44.871363 #31649] DEBUG -- : Sending find_coordinator API request 1 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.871493 #31649] DEBUG -- : Sending topic_metadata API request 1 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.871614 #31649] DEBUG -- : Waiting for response 1 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.871644 #31649] DEBUG -- : Waiting for response 1 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.872036 #31649] DEBUG -- : Received response 1 from 172.20.24.239:9092
I, [2018-11-15T11:45:44.872072 #31649]  INFO -- : Discovered cluster metadata; nodes: 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:44.872095 #31649] DEBUG -- : Closing socket to 172.20.24.239:9092
I, [2018-11-15T11:45:44.872159 #31649]  INFO -- : There are no partitions to fetch from, sleeping for 1s
D, [2018-11-15T11:45:44.873197 #31649] DEBUG -- : Received response 1 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.873270 #31649] DEBUG -- : Coordinator for `test` is 1001. Connecting...
D, [2018-11-15T11:45:44.873303 #31649] DEBUG -- : Connected to coordinator: 172.20.24.239:9092 (node_id=1001) for `test`
D, [2018-11-15T11:45:44.873351 #31649] DEBUG -- : Sending join_group API request 2 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.873439 #31649] DEBUG -- : Waiting for response 2 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.875312 #31649] DEBUG -- : Received response 2 from 172.20.24.239:9092
I, [2018-11-15T11:45:44.875363 #31649]  INFO -- : Joined group `test` with member id `ruby-kafka-05c1aa89-1129-444d-8efb-b97c51e43213`
I, [2018-11-15T11:45:44.875379 #31649]  INFO -- : Chosen as leader of group `test`
D, [2018-11-15T11:45:44.875445 #31649] DEBUG -- : Sending sync_group API request 3 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.875545 #31649] DEBUG -- : Waiting for response 3 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.877431 #31649] DEBUG -- : Received response 3 from 172.20.24.239:9092
I, [2018-11-15T11:45:44.877478 #31649]  INFO -- : Partitions assigned for `test`: 0
D, [2018-11-15T11:45:44.877536 #31649] DEBUG -- : Sending offset_fetch API request 4 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.877619 #31649] DEBUG -- : Waiting for response 4 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.878136 #31649] DEBUG -- : Received response 4 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.878249 #31649] DEBUG -- : Sending list_offset API request 5 to 172.20.24.239:9092
D, [2018-11-15T11:45:44.878337 #31649] DEBUG -- : Waiting for response 5 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.879269 #31649] DEBUG -- : Received response 5 from 172.20.24.239:9092
D, [2018-11-15T11:45:44.879350 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:45:45.872498 #31649] DEBUG -- : Handling fetcher command: reset
D, [2018-11-15T11:45:45.872670 #31649] DEBUG -- : Handling fetcher command: seek
I, [2018-11-15T11:45:45.872762 #31649]  INFO -- : Seeking test/0 to offset 0
D, [2018-11-15T11:45:45.872843 #31649] DEBUG -- : Fetching batches
I, [2018-11-15T11:45:45.873086 #31649]  INFO -- : New topics added to target list: test
I, [2018-11-15T11:45:45.873190 #31649]  INFO -- : Fetching cluster metadata from kafka://172.20.24.239:9092
D, [2018-11-15T11:45:45.873355 #31649] DEBUG -- : Opening connection to 172.20.24.239:9092 with client id ruby-kafka...
D, [2018-11-15T11:45:45.873927 #31649] DEBUG -- : Sending topic_metadata API request 1 to 172.20.24.239:9092
D, [2018-11-15T11:45:45.874304 #31649] DEBUG -- : Waiting for response 1 from 172.20.24.239:9092
D, [2018-11-15T11:45:45.876974 #31649] DEBUG -- : Received response 1 from 172.20.24.239:9092
I, [2018-11-15T11:45:45.877118 #31649]  INFO -- : Discovered cluster metadata; nodes: 172.20.24.239:9092 (node_id=1001)
D, [2018-11-15T11:45:45.877207 #31649] DEBUG -- : Closing socket to 172.20.24.239:9092
D, [2018-11-15T11:45:45.877561 #31649] DEBUG -- : Opening connection to 172.20.24.239:9092 with client id ruby-kafka...
D, [2018-11-15T11:45:45.878042 #31649] DEBUG -- : Sending fetch API request 1 to 172.20.24.239:9092
D, [2018-11-15T11:45:45.878417 #31649] DEBUG -- : Waiting for response 1 from 172.20.24.239:9092
D, [2018-11-15T11:45:45.885908 #31649] DEBUG -- : Received response 1 from 172.20.24.239:9092
D, [2018-11-15T11:45:45.886363 #31649] DEBUG -- : Fetching batches
D, [2018-11-15T11:45:45.886618 #31649] DEBUG -- : Sending fetch API request 2 to 172.20.24.239:9092
D, [2018-11-15T11:45:45.886969 #31649] DEBUG -- : Waiting for response 2 from 172.20.24.239:9092
0

Hello, World! 0
E, [2018-11-15T11:45:46.879995 #31649] ERROR -- : Exception raised when processing test/0 at offset 0 -- StandardError: StandardError
poc.rb:21:in `block in <main>'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/consumer.rb:228:in `block (4 levels) in each_message'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/instrumenter.rb:23:in `instrument'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/instrumenter.rb:35:in `instrument'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/consumer.rb:226:in `block (3 levels) in each_message'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/consumer.rb:210:in `each'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/consumer.rb:210:in `block (2 levels) in each_message'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/consumer.rb:209:in `each'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/consumer.rb:209:in `block in each_message'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/consumer.rb:395:in `block in consumer_loop'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/instrumenter.rb:23:in `instrument'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/instrumenter.rb:35:in `instrument'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/consumer.rb:394:in `consumer_loop'
/home/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/ruby-kafka-25b1060ee1be/lib/kafka/consumer.rb:206:in `each_message'
poc.rb:19:in `<main>'
I, [2018-11-15T11:45:46.880198 #31649]  INFO -- : Leaving group `test`
D, [2018-11-15T11:45:46.880332 #31649] DEBUG -- : Sending leave_group API request 6 to 172.20.24.239:9092
D, [2018-11-15T11:45:46.880686 #31649] DEBUG -- : Waiting for response 6 from 172.20.24.239:9092
D, [2018-11-15T11:45:46.885767 #31649] DEBUG -- : Received response 6 from 172.20.24.239:9092
#<Kafka::ProcessingError: Kafka::ProcessingError>
I, [2018-11-15T11:45:46.886084 #31649]  INFO -- : Joining group `test`
D, [2018-11-15T11:45:46.886218 #31649] DEBUG -- : Sending join_group API request 7 to 172.20.24.239:9092
D, [2018-11-15T11:45:46.886529 #31649] DEBUG -- : Waiting for response 7 from 172.20.24.239:9092
D, [2018-11-15T11:45:46.888098 #31649] DEBUG -- : Received response 7 from 172.20.24.239:9092
E, [2018-11-15T11:45:46.888230 #31649] ERROR -- : Failed to join group; resetting member id and retrying in 1s...
D, [2018-11-15T11:45:46.890883 #31649] DEBUG -- : Received response 2 from 172.20.24.239:9092
D, [2018-11-15T11:45:46.891057 #31649] DEBUG -- : Handling fetcher command: stop
I, [2018-11-15T11:45:46.891123 #31649]  INFO -- : Fetcher thread exited.
I, [2018-11-15T11:45:47.888428 #31649]  INFO -- : Joining group `test`
D, [2018-11-15T11:45:47.888727 #31649] DEBUG -- : Sending join_group API request 8 to 172.20.24.239:9092
D, [2018-11-15T11:45:47.889322 #31649] DEBUG -- : Waiting for response 8 from 172.20.24.239:9092
D, [2018-11-15T11:45:47.891857 #31649] DEBUG -- : Received response 8 from 172.20.24.239:9092
I, [2018-11-15T11:45:47.891911 #31649]  INFO -- : Joined group `test` with member id `ruby-kafka-06bcd4df-720f-4de6-b087-676d2bc04599`
I, [2018-11-15T11:45:47.891935 #31649]  INFO -- : Chosen as leader of group `test`
D, [2018-11-15T11:45:47.892030 #31649] DEBUG -- : Sending sync_group API request 9 to 172.20.24.239:9092
D, [2018-11-15T11:45:47.892172 #31649] DEBUG -- : Waiting for response 9 from 172.20.24.239:9092
D, [2018-11-15T11:45:47.893699 #31649] DEBUG -- : Received response 9 from 172.20.24.239:9092
I, [2018-11-15T11:45:47.893759 #31649]  INFO -- : Partitions assigned for `test`: 0
D, [2018-11-15T11:45:47.893835 #31649] DEBUG -- : Sending offset_fetch API request 10 to 172.20.24.239:9092
D, [2018-11-15T11:45:47.893946 #31649] DEBUG -- : Waiting for response 10 from 172.20.24.239:9092
D, [2018-11-15T11:45:47.894652 #31649] DEBUG -- : Received response 10 from 172.20.24.239:9092
D, [2018-11-15T11:45:47.894763 #31649] DEBUG -- : Sending list_offset API request 11 to 172.20.24.239:9092
D, [2018-11-15T11:45:47.894891 #31649] DEBUG -- : Waiting for response 11 from 172.20.24.239:9092
D, [2018-11-15T11:45:47.895509 #31649] DEBUG -- : Received response 11 from 172.20.24.239:9092
D, [2018-11-15T11:45:47.895575 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:45:49.895869 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:45:51.896244 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:45:53.896647 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:45:55.897181 #31649] DEBUG -- : Sending heartbeat...
D, [2018-11-15T11:45:55.897437 #31649] DEBUG -- : Sending heartbeat API request 12 to 172.20.24.239:9092
D, [2018-11-15T11:45:55.898025 #31649] DEBUG -- : Waiting for response 12 from 172.20.24.239:9092
D, [2018-11-15T11:45:55.901696 #31649] DEBUG -- : Received response 12 from 172.20.24.239:9092
D, [2018-11-15T11:45:55.901914 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:45:57.902322 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:45:59.902792 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:01.903117 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:03.903329 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:05.903607 #31649] DEBUG -- : Sending heartbeat...
D, [2018-11-15T11:46:05.903819 #31649] DEBUG -- : Sending heartbeat API request 13 to 172.20.24.239:9092
D, [2018-11-15T11:46:05.904195 #31649] DEBUG -- : Waiting for response 13 from 172.20.24.239:9092
D, [2018-11-15T11:46:05.906975 #31649] DEBUG -- : Received response 13 from 172.20.24.239:9092
D, [2018-11-15T11:46:05.907104 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:07.907335 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:09.907661 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:11.908041 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:13.908333 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:15.908703 #31649] DEBUG -- : Sending heartbeat...
D, [2018-11-15T11:46:15.908928 #31649] DEBUG -- : Sending heartbeat API request 14 to 172.20.24.239:9092
D, [2018-11-15T11:46:15.909339 #31649] DEBUG -- : Waiting for response 14 from 172.20.24.239:9092
D, [2018-11-15T11:46:15.912269 #31649] DEBUG -- : Received response 14 from 172.20.24.239:9092
D, [2018-11-15T11:46:15.912423 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:17.912716 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:19.913157 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:21.913562 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:23.913873 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:25.914224 #31649] DEBUG -- : Sending heartbeat...
D, [2018-11-15T11:46:25.914422 #31649] DEBUG -- : Sending heartbeat API request 15 to 172.20.24.239:9092
D, [2018-11-15T11:46:25.914780 #31649] DEBUG -- : Waiting for response 15 from 172.20.24.239:9092
D, [2018-11-15T11:46:25.917449 #31649] DEBUG -- : Received response 15 from 172.20.24.239:9092
D, [2018-11-15T11:46:25.917582 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:27.917852 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:29.918091 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:31.918532 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:33.918895 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:35.919178 #31649] DEBUG -- : Sending heartbeat...
D, [2018-11-15T11:46:35.919263 #31649] DEBUG -- : Sending heartbeat API request 16 to 172.20.24.239:9092
D, [2018-11-15T11:46:35.919428 #31649] DEBUG -- : Waiting for response 16 from 172.20.24.239:9092
D, [2018-11-15T11:46:35.920634 #31649] DEBUG -- : Received response 16 from 172.20.24.239:9092
D, [2018-11-15T11:46:35.920679 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:37.920896 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:39.921328 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:41.921588 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:43.921981 #31649] DEBUG -- : No batches to process
D, [2018-11-15T11:46:45.922429 #31649] DEBUG -- : Sending heartbeat...
D, [2018-11-15T11:46:45.922665 #31649] DEBUG -- : Sending heartbeat API request 17 to 172.20.24.239:9092
D, [2018-11-15T11:46:45.923090 #31649] DEBUG -- : Waiting for response 17 from 172.20.24.239:9092
D, [2018-11-15T11:46:45.926399 #31649] DEBUG -- : Received response 17 from 172.20.24.239:9092
D, [2018-11-15T11:46:45.926545 #31649] DEBUG -- : No batches to process
```

**Comment by dasch** [comment] 2018-11-15 11:12
We've seen this as well.

**Comment by tjwp** [comment] 2018-11-15 14:20
We hit this too.

**Comment by anujdas** [comment] 2018-11-15 23:12
I've been hitting this as well. I think that this is a race condition introduced in https://github.com/zendesk/ruby-kafka/commit/dc7a9e41c1000218bd40e8d118016f5f63de7ed4 between the consumer shutdown and fetcher shutdown. The relevant log lines in the repro posted, which match what I've been seeing, are:

```I, [2018-11-15T11:45:46.880198 #31649]  INFO -- : Leaving group `test`
I, [2018-11-15T11:45:46.886084 #31649]  INFO -- : Joining group `test`
E, [2018-11-15T11:45:46.888230 #31649] ERROR -- : Failed to join group; resetting member id and retrying in 1s...
D, [2018-11-15T11:45:46.891057 #31649] DEBUG -- : Handling fetcher command: stop
I, [2018-11-15T11:45:46.891123 #31649]  INFO -- : Fetcher thread exited.
I, [2018-11-15T11:45:47.888428 #31649]  INFO -- : Joining group `test`
I, [2018-11-15T11:45:47.891911 #31649]  INFO -- : Joined group `test` with member id `ruby-kafka-06bcd4df-720f-4de6-b087-676d2bc04599````

The consumer loop stops the fetcher, leaves the group, and then tries to rejoin and restart the fetcher. However, since stopping the fetcher is now asynchronous (based on when the fetcher thread processes the `stop` command in the tight loop https://github.com/zendesk/ruby-kafka/blob/25b1060ee1be9817353c0c3eb5d90a40d714d9da/lib/kafka/fetcher.rb#L53), it looks like the consumer manages to start back up before it's actually stopped. Unfortunately this makes the fetcher restart (https://github.com/zendesk/ruby-kafka/blob/25b1060ee1be9817353c0c3eb5d90a40d714d9da/lib/kafka/consumer.rb#L390) a no-op, after which the fetcher finally does shut down unrecoverably.

I can confirm also that 0.7.2 does not have this issue, whereas 0.7.3 (with said patch) does.

**Comment by anujdas** [comment] 2018-11-16 08:13
Just put up https://github.com/zendesk/ruby-kafka/pull/687, which in my testing fixes this issue. Two things about which I'm not sure:
- Is there any downside to waiting for the fetcher to stop? I don't see any.
- Is there a good way to test this? I'm working on adding something to the functional specs, but since it's fixing a race condition this might require running for a couple seconds and seeing if things are ok (which is not a high-confidence test).

**Comment by nguyenquangminh0711** [comment] 2018-11-17 17:18
@anujdas Joining to wait for the fetcher thread is an okay fix for this issue. However, there are some other issues rather than this one. The root cause of them comes from the asynchronous handling of fetcher's commands. They causes a period of delay between receiving the commands til processing it. I'm thinking of moving all the commands handling to foreground and just let the fetching process in background. It would be a more integrity fix.

**Closed** 2019-09-29 00:03 UTC
Labels: no-issue-activity, 🐞 bug

**Comment by mensfeld** [comment] 2022-03-16 12:40
FYI it is still a problem.
