### ISSUE TITLE
Async producer causing main process to exit

### ISSUE THREAD

**Issue by prestonwrthompson** [zendesk/ruby-kafka#312] opened 2017-01-10 23:26 UTC
I have a question about the design of the async producer. 

For context, in our set up, we have our job processing code running in a main process, and most of the jobs result in at least one message that we want to produce to Kafka. From this main process, we call `produce` on the async producer.

The async producer spawns two threads, the timer thread and the worker thread. The problem we are having is that whenever there is an uncaught exception from the synchronous producer in the worker thread (specifically, we received `Kafka::Error, "Correlation id mismatch"` from [here](https://github.com/zendesk/ruby-kafka/blob/2d7812cf1dd0e18130412c9518e400347c4e5a53/lib/kafka/connection.rb#L190)), the main process crashes. We've tracked it down to the async producer setting `abort_on_exception` to true on the worker thread [here](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/async_producer.rb#L151) in `async_producer.rb`.

Here is the documentation for `abort_on_exception` for an instance of a thread:
> When set to true, causes all threads (including the main program) to abort if an exception is raised in `thr`. The process will effectively `exit(0)`.

And here is the documentation for `abort_on_exception` on the `Thread` class:
>Returns the status of the global `abort on exception` condition. The default is false. When set to true, will cause all threads to abort (the process will `exit(0)`) if an exception is raised in any thread. See also `Thread.abort_on_exception=` .

From the documentation, it seems like there's no way to avoid ruby-kafka causing the main process to`exit(0)` if there's an uncaught exception in the worker thread. Is that true or is there a way to prevent it? Can you explain the design decision behind setting `abort_on_exception` to true?

**Comment by dasch** [comment] 2017-01-13 22:13
Let me look at it Monday - this is definitely not the intended behavior. Are you using the latest version?

**Comment by prestonwrthompson** [comment] 2017-01-14 21:03
Thanks. Yes, I just tested now on 0.3.15 and master. Here are simple steps to reproduce.

```
AB-C02N4MLLG3QC:ruby-kafka preston$ irb
irb(main):001:0> require "ruby-kafka"
=> true
irb(main):002:0> kafka = Kafka::Client.new(:seed_brokers => ["kafka:9092"])
=> #<Kafka::Client:0x007ff87c57e640 [removed for readability]>
irb(main):003:0> async_producer = kafka.async_producer(:delivery_interval => 5)
=> #<Kafka::AsyncProducer:0x007ff87f00f5f8 [removed for readability]>
irb(main):004:0> async_producer.produce("abc", :topic => "ruby_kafka_test")
=> nil
## i waited to confirm "abc" was produced to the topic
irb(main):005:0> async_producer.produce(123, :topic => "ruby_kafka_test")
=> nil
## within 5 seconds (the delivery interval), this exception is raised
irb(main):006:0> /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/encoder.rb:94:in `write_bytes': undefined method `bytesize' for 123:Fixnum (NoMethodError)
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/message.rb:106:in `encode_without_crc'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/message.rb:90:in `encode_with_crc'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/message.rb:34:in `encode'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/message_set.rb:22:in `block in encode'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/message_set.rb:21:in `each'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/message_set.rb:21:in `encode'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/encoder.rb:107:in `encode_with'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/produce_request.rb:68:in `block (2 levels) in encode'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/encoder.rb:70:in `each'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/encoder.rb:70:in `write_array'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/produce_request.rb:62:in `block in encode'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/encoder.rb:70:in `each'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/encoder.rb:70:in `write_array'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/produce_request.rb:59:in `encode'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/request_message.rb:20:in `encode'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/protocol/encoder.rb:107:in `encode_with'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/connection.rb:142:in `write_request'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/connection.rb:91:in `block in send_request'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `call'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `instrument'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/connection.rb:86:in `send_request'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/broker.rb:60:in `produce'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/produce_operation.rb:93:in `block in send_buffered_messages'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/produce_operation.rb:79:in `each'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/produce_operation.rb:79:in `send_buffered_messages'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/produce_operation.rb:45:in `block in execute'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `call'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `instrument'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/produce_operation.rb:39:in `execute'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:301:in `block in deliver_messages_with_retries'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:293:in `loop'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:293:in `deliver_messages_with_retries'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:243:in `block in deliver_messages'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `call'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/instrumenter.rb:21:in `instrument'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:236:in `deliver_messages'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/async_producer.rb:223:in `deliver_messages'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/async_producer.rb:198:in `block in run'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/async_producer.rb:190:in `loop'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/async_producer.rb:190:in `run'
	from /Users/preston/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-kafka-0.3.15/lib/kafka/async_producer.rb:143:in `block in ensure_threads_running!'
AB-C02N4MLLG3QC:ruby-kafka preston$
```
After calling `produce` the first time, I wait to confirm the message is delivered correctly. Then, after calling `produce` the second time and waiting for the 5 second interval to trigger the worker thread to attempt to deliver the message, it crashes the process and kicks me out of the `irb` shell. Obviously, in my example trying to produce a number and not a string is wrong, but it's a reliable way to create an error. Any other uncaught error would cause the same to happen.

I forked the repo and created a quick patch ([code diff here](https://github.com/zendesk/ruby-kafka/compare/master...prestonwrthompson:master)) that raises the exception in the calling thread the next time it calls `#produce`. Probably not the best solution but figured I would at least share.

**Comment by dasch** [comment] 2017-01-16 09:24
Can you create a PR with this change, ideally with a spec?

**Comment by prestonwrthompson** [comment] 2017-01-17 05:51
Yup, will work on it tomorrow

**Comment by prestonwrthompson** [comment] 2017-01-18 06:40
Sorry, some other things came up and I wasn't able to get to this today but will work to get a PR out by the end of this week

**Comment by dasch** [comment] 2017-01-18 09:31
@prestonwrthompson no worries, I'm pretty busy myself these days, not a lot of time for ruby-kafka I'm afraid.

**Comment by dasch** [comment] 2017-08-04 09:25
@prestonwrthompson is this still a problem or can I close this?

**Comment by prestonwrthompson** [comment] 2017-08-04 15:22
hey, sorry for dropping off here, i was having a bit of trouble getting a passing spec because of the threading. i have not tried to reproduce since, and we have been using my fork with the patch above. i'm not sure if it's still a problem but i assume it is because this line https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/async_producer.rb#L151 is still in the code.

**Comment by dasch** [comment] 2017-08-07 09:04
@prestonwrthompson I think the cause of the error is weird:

> ruby-kafka-0.3.15/lib/kafka/protocol/encoder.rb:94:in `write_bytes': undefined method `bytesize' for 123:Fixnum (NoMethodError)

It would seem that you're writing integers rather than strings to the producer, e.g. `producer.produce(42)`.

I think a simpler fix would be to just call `#to_s` on these arguments.

**Comment by dasch** [comment] 2017-08-07 09:21
@prestonwrthompson can you try with #384 and see if that fixes your problem?

**Comment by prestonwrthompson** [comment] 2017-08-08 14:43
hey @dasch, as i mentioned above writing an integer was just a reliable way to produce an error, but other uncaught errors would produce the same effect. here is an example stacktrace from when we were seeing it on our servers that was causing the exit.
```
Jan 04 21:06:50   Correlation id mismatch: expected 0 but got 2
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/connection.rb:210:in `block in wait_for_response'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/connection.rb:200:in `loop'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/connection.rb:200:in `wait_for_response'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/connection.rb:94:in `block in send_request'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/instrumenter.rb:19:in `instrument'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/connection.rb:86:in `send_request'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/broker.rb:60:in `produce'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/produce_operation.rb:93:in `block in send_buffered_messages'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/produce_operation.rb:79:in `each'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/produce_operation.rb:79:in `send_buffered_messages'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/produce_operation.rb:45:in `block in execute'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/instrumenter.rb:19:in `instrument'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/produce_operation.rb:39:in `execute'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/producer.rb:298:in `block in deliver_messages_with_retries'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/producer.rb:290:in `loop'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/producer.rb:290:in `deliver_messages_with_retries'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/producer.rb:240:in `block in deliver_messages'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/instrumenter.rb:19:in `instrument'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/producer.rb:233:in `deliver_messages'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/async_producer.rb:213:in `deliver_messages'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/async_producer.rb:188:in `block in run'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/async_producer.rb:180:in `loop'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/async_producer.rb:180:in `run'
Jan 04 21:06:50   /opt/bundle/ruby/2.2.0/gems/ruby-kafka-0.3.12/lib/kafka/async_producer.rb:135:in `block in ensure_threads_running!'
```

**Comment by dasch** [comment] 2017-08-08 19:13
@prestonwrthompson by design, the async producer should handle any such error without impacting the caller – but also without silently dying. I think the right approach is to handle such exceptions, perhaps restarting the producer if need be. In this case, I'm not sure how we'd get the wrong correlation id – is this something you can reproduce?

Perhaps it would make sense to rescue that error specifically and simply retry the request.

**Comment by film42** [comment] 2017-09-28 15:03
@dasch In the past I've solved this in projects by exposing an `error_handler` callback (configurable by the user) which the publisher can invoke if an error occurs. By default it just logs to the logger. But this also let's the user send those errors to an exception monitoring service like honey badger. This is essentially the same thing as `abort_on_exception` but better for service availability. I'm happy to open a PR if you're interested.

Here's an example of the above, btw:

https://github.com/mxenabled/active_publisher/blob/7874811d795b4ab65a4ebb9f16b466447c3d870b/lib/active_publisher/configuration.rb#L26-L30

https://github.com/mxenabled/active_publisher/blob/7874811d795b4ab65a4ebb9f16b466447c3d870b/lib/active_publisher/async/in_memory_adapter/consumer_thread.rb#L75-L76

**Comment by film42** [comment] 2017-10-19 15:03
This shouldn't be a problem anymore after https://github.com/zendesk/ruby-kafka/pull/432

**Closed** 2017-10-20 09:30 UTC
Labels: bug

**Comment by prestonwrthompson** [comment] 2017-10-20 15:20
thanks @film42 and @dasch!
