### ISSUE TITLE
Timestamp support for Kafka 0.10.2.0

### ISSUE THREAD

**Issue by sophia-d** [zendesk/ruby-kafka#331] opened 2017-03-20 22:38 UTC
Hi, 
Recently upgraded the Kafka server to 0.10.2.0, and the message timestamp turns out to be a showstopper with this gem. We need a ruby-kafka gem for the producer app, so any word on what the status on adding the timestamp support is? 

Any help on this issue is much appreciated! 
(If you or anyone has any alternate ways to work around it, please advise! Thanks!

**Comment by dasch** [comment] 2017-03-22 18:42
For now, you should be able to use the branch in https://github.com/zendesk/ruby-kafka/pull/279

This gem still primarily targets Kafka 0.10 - I expect to move it to 0.10 in the coming months, though.

**Comment by sophia-d** [comment] 2017-03-22 19:07
Thanks Daniel. I tried the branch in #270 after reading up and down all the issues here.. :) That branch didn't work for me using Kafka broker 0.10.2 - the messages weren't getting processed at all on the consumer KStreams app, and even the useful error messages/exceptions that I get with this gem, I can't get using the other branch. Seemed like a lost case, and running out of time, I had to switch back to this gem for now, and roll back to Kafka 0.10.1. So.. I think you get the picture here: WE NEED this gem to get updated :) The compatibility wall with Kafka hits at Kafka 0.10.2.

**Comment by prestonwrthompson** [comment] 2017-03-22 19:21
Not sure if this will help you, but you can alter the `message.timestamp.type` config on a per topic basis to `CreateTime`. This will have the brokers use the time that a message is ingested into Kafka as the message's timestamp. For topics produced to by ruby-kafka, you can use this command
```
bin/kafka-configs --alter --entity-name test_topic --entity-type topics --add-config message.timestamp.type=CreateTime --zookeeper localhost:2181
```

**Comment by az3** [comment] 2017-03-23 15:05
@prestonwrthompson 
Maybe you can use `LogAppendTime`, instead of `CreateTime` in TimestampType value.
```
bin/kafka-configs --alter --entity-name test_topic --entity-type topics --add-config message.timestamp.type=LogAppendTime --zookeeper localhost:2181
```

**Comment by prestonwrthompson** [comment] 2017-03-23 15:17
yeah, thanks for catching that. i meant to suggest changing the config to `LogAppendTime`, not `CreateTime`

**Comment by sophia-d** [comment] 2017-04-05 16:39
Thanks all for your help.. We wound up rolling back to Kafka 0.10.1.0 due to incompatibility w/ this gem. Will upgrade when this gets upgraded.

**Comment by dasch** [comment] 2017-04-06 11:04
@sophia-d it's likely that I'll work on upgrading ruby-kafka to Kafka protocol version 0.10 this month.

**Comment by Elyahou** [comment] 2017-05-21 14:22
Hey @dasch do you have any update on the upgrade ? Thanks

**Comment by dasch** [comment] 2017-05-21 19:23
I don't, I'm afraid - I don't have a production 0.10 cluster to test
against yet. Once I do I'll figure out a way to move to support that
version.

**Comment by sparrovv** [comment] 2017-07-12 12:50
hey @dasch, is there any chance to get a support for 0.10.2 in the upcoming weeks? Thanks!

**Comment by dasch** [comment] 2017-07-17 11:41
Duplicate of #270

**Comment by dasch** [comment] 2017-07-20 13:28
Resolved by #376.

**Closed by dasch** 2017-07-20 13:28 UTC

**Comment by dasch** [comment] 2017-07-20 17:19
@sophia-d I've just released `v0.5.0.beta1` with support for Kafka 0.10. Would you be willing to run this in production for some time and see if everything works as expected?

**Comment by sophia-d** [comment] 2017-07-20 17:48
Hi @dasch, yes will give it a test run.. Mind that the biggest difference was the leap from Kafka 0.10.1 to 0.10.2. I already am using the gem as is for Kafka 0.10.1.

**Comment by dasch** [comment] 2017-07-20 18:02
@sophia-d was there a change in the wire protocol in v0.10.2? Otherwise it should work just as well, unless there's a bug in that version of Kafka.

The new thing in ruby-kafka v0.5 is that it uses the Kafka 0.10 message format, which should improve performance but would also be the source of any breakage. Everything looks fine in my testing, though, but it's nice to validate against a real cluster.
